export const marioData = [
    {id: 1, titulo: 'Super Mario Bros', img:'https://i.imgur.com/NmgSZPc.png'},
    {id: 2, titulo: 'Super Mario Bros 2 (Lost Levels)', img:'https://i.imgur.com/qb1KInb.jpg'},
    {id: 3, titulo: 'Super Mario Bros 2', img:'https://i.imgur.com/RbyX6S6.png'},
    {id: 4, titulo: 'Super Mario Bros 3', img: 'https://i.imgur.com/eve5j9E.jpg'},
    {id: 5, titulo: 'Super Mario Land', img: 'https://i.imgur.com/Sif9Ys6.jpg'},
    {id: 6, titulo: 'Dr. Mario', img: 'https://i.imgur.com/vb51at1.jpg'},
    {id: 7, titulo: 'Super Mario World', img: 'https://i.imgur.com/SfPx7f6.jpg'},
    {id: 8, titulo: 'Super Mario Land 2', img: 'https://i.imgur.com/lbrRLTb.jpg'},
    {id: 9, titulo: 'Super Mario Kart', img: 'https://i.imgur.com/lczo9zv.jpg'},
    {id: 10, titulo: 'Super Mario 64', img: 'https://i.imgur.com/dslt9o5.jpg'},
    {id: 11, titulo: 'Mario Slam Basketball', img: 'https://i.imgur.com/Ncsdkd1.jpg'},
    {id: 12, titulo: 'Paper Mario', img:'https://i.imgur.com/R6qSj0p.jpg' },
    {id: 13, titulo: 'Super Mario Sunshine', img: 'https://i.imgur.com/Le1pbEX.jpg'},
    {id: 14, titulo: 'Mario & Luigi: Superstar Saga', img:'https://i.imgur.com/d7OSakP.jpg'},
    {id: 15, titulo: 'Mario vs Donkey Kong', img: 'https://i.imgur.com/8Eatt7i.jpg'},
    {id: 16, titulo: 'Super Mario Galaxy', img: 'https://i.imgur.com/9PJqkvW.jpg'},
    {id: 17, titulo: 'Super Mario Galaxy 2', img: 'https://i.imgur.com/NvbEOac.png'},
    {id: 18, titulo: 'Super Mario Maker', img: 'https://i.imgur.com/1b4iUjP.jpg'},
    {id: 19, titulo: 'Super Mario Maker 2', img: 'https://i.imgur.com/tyqSeAn.jpg'},
    {id: 20, titulo: 'Mario vs Donkey Kong Remake', img: 'https://www.nintenderos.com/wp-content/uploads/2024/02/mario-vs-donkey-kong.jpg.webp'},
]